// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv6uShjt3khXqpTO7E45UkbS0LoB2-Tn0',
    appId: '1:628767079914:web:552a3d790268ce25f58693',
    messagingSenderId: '628767079914',
    projectId: 'pril123',
    authDomain: 'pril123.firebaseapp.com',
    storageBucket: 'pril123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzjqGwZ8BF6sU3__gyl4BlkDuajM-QZSU',
    appId: '1:628767079914:android:50e447211c0dc1cef58693',
    messagingSenderId: '628767079914',
    projectId: 'pril123',
    storageBucket: 'pril123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7NLz5HPfZhPmN-LIyez3o3rw-GIobDLQ',
    appId: '1:628767079914:ios:2e53da72a20cb9e0f58693',
    messagingSenderId: '628767079914',
    projectId: 'pril123',
    storageBucket: 'pril123.firebasestorage.app',
    iosBundleId: 'com.example.liniya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7NLz5HPfZhPmN-LIyez3o3rw-GIobDLQ',
    appId: '1:628767079914:ios:2e53da72a20cb9e0f58693',
    messagingSenderId: '628767079914',
    projectId: 'pril123',
    storageBucket: 'pril123.firebasestorage.app',
    iosBundleId: 'com.example.liniya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv6uShjt3khXqpTO7E45UkbS0LoB2-Tn0',
    appId: '1:628767079914:web:a002f66bcbcccde5f58693',
    messagingSenderId: '628767079914',
    projectId: 'pril123',
    authDomain: 'pril123.firebaseapp.com',
    storageBucket: 'pril123.firebasestorage.app',
  );
}
